server:
  port: 8080

spring:
  application:
    name: liar-game
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # security:
  #   jwt:
  #     secret-key: liargame-secret-key-for-jwt-token-generation-2023
  #     expiration-time: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.liargame: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG